from .user_model import UserModel
from .user_qr_code_model import UserQRCodeModel
from .verification_code_model import VerificationCodeModel
from .verification_code_password_reset_model import VerificationCodePasswordResetModel
from .user_favorite_model import UserFavoriteModel

UserModel.model_rebuild()
UserQRCodeModel.model_rebuild()
VerificationCodeModel.model_rebuild()
VerificationCodePasswordResetModel.model_rebuild()
UserFavoriteModel.model_rebuild()
