"""change_user_id_to_uuid_clean

Revision ID: 410de5d74c6b
Revises: add_created_updated_at
Create Date: 2025-10-01 05:42:51.763630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '410de5d74c6b'
down_revision: Union[str, Sequence[str], None] = 'add_created_updated_at'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customization_groups', sa.Column('id', sa.Uuid(), nullable=False))
    op.alter_column('customization_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('customization_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('customization_groups', 'group_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.add_column('customization_options', sa.Column('id', sa.Uuid(), nullable=False))
    op.alter_column('customization_options', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('customization_options', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('customization_options', 'option_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.add_column('ingredients', sa.Column('id', sa.Uuid(), nullable=False))
    op.alter_column('ingredients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('ingredients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('order_item', sa.Column('id', sa.Uuid(), nullable=False))
    op.alter_column('order_item', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('order_item', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('order_item_customization', 'created_at')
    op.drop_column('order_item_customization', 'updated_at')
    op.add_column('orders', sa.Column('id', sa.Uuid(), nullable=False))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('orders', 'order_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.add_column('product_categories', sa.Column('id', sa.Uuid(), nullable=False))
    op.alter_column('product_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('product_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('product_category_link', 'created_at')
    op.drop_column('product_category_link', 'updated_at')
    op.drop_column('product_customization_groups', 'created_at')
    op.drop_column('product_customization_groups', 'updated_at')
    op.add_column('product_ingredients', sa.Column('id', sa.Uuid(), nullable=False))
    op.alter_column('product_ingredients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('product_ingredients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('product_promotions', sa.Column('id', sa.Uuid(), nullable=False))
    op.alter_column('product_promotions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('product_promotions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('products', sa.Column('id', sa.Uuid(), nullable=False))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('products', 'product_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.add_column('promotions', sa.Column('id', sa.Uuid(), nullable=False))
    op.add_column('promotions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('promotions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('user_qr_codes', sa.Column('id', sa.Uuid(), nullable=False))
    op.add_column('user_qr_codes', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('id', sa.Uuid(), nullable=False))
    
    # Para evitar problemas de conversión, simplemente eliminamos la tabla users y la recreamos
    # En desarrollo es aceptable porque no tenemos datos críticos
    op.execute("DROP TABLE IF EXISTS users CASCADE")
    
    # Recrear la tabla users con UUID - usar el enum existente
    op.execute("""
        CREATE TABLE users (
            id UUID NOT NULL,
            user_id UUID NOT NULL,
            role userrole NOT NULL DEFAULT 'customer',
            name VARCHAR NOT NULL,
            last_name VARCHAR NOT NULL,
            birth_date DATE NOT NULL,
            email VARCHAR NOT NULL,
            password VARCHAR NOT NULL,
            points FLOAT NOT NULL DEFAULT 0.0,
            is_verified BOOLEAN NOT NULL DEFAULT false,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (user_id),
            UNIQUE (email)
        )
    """)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.add_column('verification_codes', sa.Column('id', sa.Uuid(), nullable=False))
    op.alter_column('verification_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('verification_codes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('verification_codes_password_reset', sa.Column('id', sa.Uuid(), nullable=False))
    op.add_column('verification_codes_password_reset', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('verification_codes_password_reset', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_codes_password_reset', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('verification_codes_password_reset', 'updated_at')
    op.drop_column('verification_codes_password_reset', 'id')
    op.alter_column('verification_codes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('verification_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('verification_codes', 'id')
    op.alter_column('users', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('users', 'id')
    op.drop_column('user_qr_codes', 'updated_at')
    op.drop_column('user_qr_codes', 'id')
    op.alter_column('promotions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('promotions', 'created_at')
    op.drop_column('promotions', 'id')
    op.alter_column('products', 'product_id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('products_product_id_seq'::regclass)"),
               existing_nullable=False)
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'id')
    op.alter_column('product_promotions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('product_promotions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('product_promotions', 'id')
    op.alter_column('product_ingredients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('product_ingredients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('product_ingredients', 'id')
    op.add_column('product_customization_groups', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('product_customization_groups', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('product_category_link', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('product_category_link', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('product_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('product_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('product_categories', 'id')
    op.alter_column('orders', 'order_id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('orders_order_id_seq'::regclass)"),
               existing_nullable=False)
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('orders', 'id')
    op.add_column('order_item_customization', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('order_item_customization', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('order_item', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('order_item', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('order_item', 'id')
    op.alter_column('ingredients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('ingredients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('ingredients', 'id')
    op.alter_column('customization_options', 'option_id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('customization_options_option_id_seq'::regclass)"),
               existing_nullable=False)
    op.alter_column('customization_options', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('customization_options', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('customization_options', 'id')
    op.alter_column('customization_groups', 'group_id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('customization_groups_group_id_seq'::regclass)"),
               existing_nullable=False)
    op.alter_column('customization_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('customization_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('customization_groups', 'id')
    # ### end Alembic commands ###
