"""sync models with db

Revision ID: 461c73d42bca
Revises: 5f007c089a82
Create Date: 2025-10-14 19:34:14.689278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '461c73d42bca'
down_revision: Union[str, Sequence[str], None] = '5f007c089a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customization_options', sa.Column('is_size_option', sa.Boolean(), nullable=False))
    op.add_column('customization_options', sa.Column('consumed_ingredient_id', sa.Uuid(), nullable=True))
    op.add_column('customization_options', sa.Column('quantity_consumed', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'customization_options', 'ingredients', ['consumed_ingredient_id'], ['ingredient_id'])
    # Crear el tipo ENUM antes de agregar la columna
    paymenttype_enum = sa.Enum('efectivo', 'tarjeta', 'puntos', name='paymenttype')
    paymenttype_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('orders', sa.Column('payment_type', paymenttype_enum, nullable=False))
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('orders', 'payment_type')
    op.drop_constraint(None, 'customization_options', type_='foreignkey')
    op.drop_column('customization_options', 'quantity_consumed')
    op.drop_column('customization_options', 'consumed_ingredient_id')
    op.drop_column('customization_options', 'is_size_option')
    # ### end Alembic commands ###
