"""add inventory, customization, orders, promotions tables

Revision ID: 5f007c089a82
Revises: 710f35a70e2e
Create Date: 2025-09-30 18:07:05.991812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5f007c089a82'
down_revision: Union[str, Sequence[str], None] = '710f35a70e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customization_groups',
    sa.Column('group_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index(op.f('ix_customization_groups_group_id'), 'customization_groups', ['group_id'], unique=False)
    op.create_table('ingredients',
    sa.Column('ingredient_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit_of_measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stock_current_level', sa.Integer(), nullable=False),
    sa.Column('stock_optimal_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.create_index(op.f('ix_ingredients_ingredient_id'), 'ingredients', ['ingredient_id'], unique=False)
    op.create_table('promotions',
    sa.Column('promotion_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('discount_type', sa.Enum('percentage', 'fixed_amount', name='discounttype'), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('promotion_id')
    )
    op.create_index(op.f('ix_promotions_promotion_id'), 'promotions', ['promotion_id'], unique=False)
    op.create_table('customization_options',
    sa.Column('option_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('group_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra_cost', sa.Float(), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['customization_groups.group_id'], ),
    sa.PrimaryKeyConstraint('option_id')
    )
    op.create_index(op.f('ix_customization_options_option_id'), 'customization_options', ['option_id'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pendiente', 'pagado', 'entregado', 'cancelado', name='orderstatus'), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('points_earned', sa.Float(), nullable=False),
    sa.Column('items_summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    op.create_table('product_customization_groups',
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('group_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['customization_groups.group_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'group_id')
    )
    op.create_table('product_ingredients',
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ingredient_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('quantity_required', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'ingredient_id')
    )
    op.create_table('product_promotions',
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('promotion_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.promotion_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'promotion_id')
    )
    op.create_table('order_item',
    sa.Column('order_item_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_purchase', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_index(op.f('ix_order_item_order_item_id'), 'order_item', ['order_item_id'], unique=False)
    op.create_table('points_used',
    sa.Column('points_used_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('points_used', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('points_used_id')
    )
    op.create_index(op.f('ix_points_used_points_used_id'), 'points_used', ['points_used_id'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', name='transactionstatus'), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=False)
    op.create_table('order_item_customization',
    sa.Column('order_item_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('option_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('extra_cost_at_purchase', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['customization_options.option_id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_item.order_item_id'], ),
    sa.PrimaryKeyConstraint('order_item_id', 'option_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item_customization')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_points_used_points_used_id'), table_name='points_used')
    op.drop_table('points_used')
    op.drop_index(op.f('ix_order_item_order_item_id'), table_name='order_item')
    op.drop_table('order_item')
    op.drop_table('product_promotions')
    op.drop_table('product_ingredients')
    op.drop_table('product_customization_groups')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_customization_options_option_id'), table_name='customization_options')
    op.drop_table('customization_options')
    op.drop_index(op.f('ix_promotions_promotion_id'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_ingredients_ingredient_id'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_customization_groups_group_id'), table_name='customization_groups')
    op.drop_table('customization_groups')
    # ### end Alembic commands ###
